export const BAIRROS_JOINVILLE = [
  "Adhemar Garcia",
  "América",
  "Anita Garibaldi",
  "Atiradores",
  "Aventureiro",
  "Boa Vista",
  "Boehmerwald",
  "Bom Retiro",
  "Bucarein",
  "Centro",
  "Comasa",
  "Costa e Silva",
  "Dona Francisca",
  "Espinheiros",
  "Fátima",
  "Floresta",
  "Glória",
  "Guanabara",
  "Iririú",
  "Itaum",
  "Itinga",
  "Jardim Iririú",
  "Jardim Paraíso",
  "Jardim Sofia",
  "Jarivatuba",
  "Jativoca",
  "João Costa",
  "Marinas",
  "Morro do Meio",
  "Nova Brasília",
  "Paranaguamirim",
  "Parque Guarani",
  "Petrópolis",
  "Pirabeiraba",
  "Profipo",
  "Saguaçu",
  "Santa Catarina",
  "Santo Antônio",
  "São Marcos",
  "Ulysses Guimarães",
  "Vale Verde",
  "Vila Cubatão",
  "Vila Nova",
  "Zona Industrial Norte",
  "Zona Industrial Tupy",
] as const;

export const AREA_RURAL = "Área Rural" as const;

export const BAIRROS_OPCOES = [...BAIRROS_JOINVILLE, AREA_RURAL] as const;

export type BairroOpcao = (typeof BAIRROS_OPCOES)[number];
